language: cpp
dist: bionic

before_script:
  - $CXX --version

before_install:
  - sudo apt-get -y install libspdlog-dev
  - sudo apt-get -y install libboost-all-dev
script:
  - mkdir build && cd ./build
  - cmake ..
  - make
  
branches:
  only:
  - master
  
notifications:
  email: false
